version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gameforge_postgres
    restart: always
    environment:
      POSTGRES_DB: gameforge
      POSTGRES_USER: gameforge_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - gameforge_network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: gameforge_backend
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://gameforge_user:${DB_PASSWORD}@postgres:5432/gameforge
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: https://518178.com
      PORT: 3000
      ADMIN_EMAIL: admin@518178.com
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - gameforge_network

  nginx:
    image: nginx:alpine
    container_name: gameforge_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ../dist:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - gameforge_network

volumes:
  postgres_data:
  backend_uploads:

networks:
  gameforge_network:
    driver: bridge